run:
  timeout: 10m
  skip-dirs:
    - holster


linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Disabled by default
    - asasalint
    - asciicheck
    - bodyclose
    - errorlint
    - gci
    - gocyclo
    - gosec
    - makezero
    - noctx
    - paralleltest
    - prealloc
    - reassign
    - revive
    - whitespace
    - wsl

issues:
  max-issues-per-linter: 0 # Unlimited
  max-same-issues: 0 # Unlimited

# Not working with our version (requires 1.57), see https://github.com/golangci/golangci-lint/pull/4509
#  exclude-dirs:
#    - holster
